export const locations = {
  login: "/login",
  starDetails: "/:id",
  signupType: "/signuptype",
  signUp: "/signup",
  recordVideo: "/recordvideo",
  requestVideo: "/:id/request",
  askQuestion: "/:id/request/ask",
  event: "/:id/request/event",
  personal: "/:id/request/personal",
  confirm: "/:id/request/confirm",
  favorites: "/user/favorites",
  myVideos: "/user/myVideos",
  unauthorized: "/unauthorized",
  notFound: "/not-found",
  getAwsVideoCredentials: "v1/user/signed_url/?extension=mp4&key=authentication_videos&file_type=video",
  askAwsVideoCredentials: "v1/user/signed_url/?extension=mp4&key=stargram_videos&file_type=video",
  bannerVideo: 'https://s3.amazonaws.com/starsona/videos/Public+Videos/banner-video.mp4',
};
