version: '3.3'
services:
  web-nginx:
    image: web-nginx-${DEPLOYMENT_TYPE}
    hostname: ${SSL_SERVER_NAME}
    volumes:
    - /etc/letsencrypt
    networks:
    - overlay
    ports:
    - "${HTTP_PORT:-80}:80"
    - "${HTTPS_PORT:-443}:443"
    restart: on-failure
    environment:
    - SSL_SERVER_NAME
    - SSL_SERVER_EMAIL
    - API_URL
    - SERVER_URL
    - STRIPE_PUBLISH_KEY
    - BRANCH_IO_KEY
    - DOMAIN_NAME=$SSL_SERVER_NAME
    - HTPASSWD
    - PRERENDER_TOKEN
    - GOOGLE_TAG_MANAGER_ID
    - HTTP_PORT
    - ROLLBAR_ENV
    - ANDROID_APP_ID
    - IOS_APP_ID
    - ANDROID_APP_NAME
    - IOS_APP_NAME

networks:
  overlay:

