import React from 'react';
import PropTypes from 'prop-types';
import { Scrollbars } from 'react-custom-scrollbars';
import PrimaryButton from '../../../PrimaryButton';
import TermsConditionsWrapper from './styled';
import { TERMS } from './constants';

export const TermsAndConditions = props => (
  <TermsConditionsWrapper>
    <TermsConditionsWrapper.ComponentWrapper>
      <TermsConditionsWrapper.HeaderText>
        {TERMS.TITLE}
      </TermsConditionsWrapper.HeaderText>
      <Scrollbars className="terms-wrapper">
      <TermsConditionsWrapper.Description>
		<h4><strong>Basic Terms</strong></h4>
<p>You must be at least 13 years old to use Starsona’s service (the “Service”).</p>
<p>You may not post unlawful, hateful, discriminatory, violent, infringing, nude, partially nude, pornographic, or sexually suggestive photos or other content via the Service.</p>
<p>If you request a video from a Star, you agree and acknowledge that Starsona and/or the Star will suffer irreparable harm if you use the Service to directly, or indirectly, get the Star to post such content and that Starsona shall be entitled, in addition to any other right and remedy it may have, at law or equity, to an injunction enjoining and restraining you from continuing to post or distribute such content without the necessity of Starsona and/or the Star posting a bond. Moreover, you agree that any award of injunctive relief shall not preclude Starsona from automatically charging your payment method on file for initial compensatory damages equal to a minimum of 10 times the cost of your video, which in no case shall be less than Five Thousand Dollars ($5,000). This shall not preclude Starsona and/or the Star from seeking additional compensatory damages.</p>
<p>You are responsible for any activity that occurs through your account and you agree you will not sell, transfer, license or assign your account, followers, username, or any account rights. With the exception of people or businesses that are expressly authorized to create accounts on behalf of their employers or clients, Starsona prohibits the creation of and you agree that you will not create an account for anyone other than yourself. You also represent that all information you provide or provided to Starsona upon registration and at all other times will be true, accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.</p>
<p>You agree that you will not solicit, collect or use the login credentials of other Starsona users.</p>
<p>You are responsible for keeping your password secret and secure.</p>
<p>You must not defame, stalk, bully, abuse, harass, threaten, impersonate or intimidate people or entities and you must not post private or confidential information via the Service, including, without limitation, your or any other person’s credit card information, social security or alternate national identity numbers, non-public phone numbers or non-public email addresses.</p>
<p>You may not use the Service for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (for example, federal, state, local and provincial) applicable to your use of the Service and your Content (defined below), including but not limited to, copyright laws.</p>
<p>You are solely responsible for your conduct and any data, text, files, information, usernames, images, graphics, photos, profiles, audio and video clips, sounds, musical works, works of authorship, applications, links and other content or materials (collectively, “Content”) that you submit, post or display on or via the Service.</p>
<p>You must not change, modify, adapt or alter the Service or change, modify or alter another website so as to falsely imply that it is associated with the Service or Starsona.</p>
<p>You must not create or submit unwanted email, comments, likes or other forms of commercial or harassing communications (a/k/a “spam”) to any Starsona users.</p>
<p>You must not use domain names or web URLs in your username without prior written consent from Starsona.</p>
<p>You must not interfere or disrupt the Service or servers or networks connected to the Service, including by transmitting any worms, viruses, spyware, malware or any other code of a destructive or disruptive nature. You may not inject content or code or otherwise alter or interfere with the way any Starsona page is rendered or displayed in a user’s browser or device.</p>
<p>You must comply with Starsona’s Community Guidelines.</p>
<p>You must not create accounts with the Service through unauthorized means, including but not limited to, by using an automated device, script, bot, spider, crawler or scraper.</p>
<p>You must not attempt to restrict another user from using or enjoying the Service and you must not encourage or facilitate violations of these Terms of Service or any other Starsona terms.</p>
<p>Violation of these Terms of Service may, in Starsona’s sole discretion, result in termination of your Starsona account. You understand and agree that Starsona cannot and will not be responsible for the Content posted on the Service and you use the Service at your own risk. If you violate the letter or spirit of these Terms of Service, or otherwise create risk or possible legal exposure for Starsona, we can stop providing all or part of the Service to you.</p>
<p>&nbsp;</p>
<h4>General Conditions</h4>
<p>We reserve the right to modify or terminate the Service or your access to the Service for any reason, without notice, at any time, and without liability to you. You can deactivate your Starsona account by sending an email to: support@starsona.com. If we terminate your access to the Service or you use the form detailed above to deactivate your account, your videos, photos, comments, likes, friendships, and all other data will no longer be accessible through your account, but those materials and data may persist and appear within the Service (e.g., if your Content has been re-shared by others).</p>
<p>Upon termination, all licenses and other rights granted to you in these Terms of Service will immediately cease.</p>
<p>We reserve the right to refuse access to the Service to anyone for any reason at any time.</p>
<p>We reserve the right, in our sole discretion, to change these Terms of Service (“Updated Terms”) from time to time. Unless we make a change for legal or administrative reasons, we will provide reasonable advance notice before the Updated Terms become effective. You agree that we may notify you of the Updated Terms by posting them on the Service, and that your use of the Service after the effective date of the Updated Terms (or engaging in such other conduct as we may reasonably specify) constitutes your agreement to the Updated Terms. Therefore, you should review these Terms of Service and any Updated Terms before using the Service. The Updated Terms will be effective as of the time of posting, or such later date as may be specified in the Updated Terms, and will apply to your use of the Service from that point forward. These Terms of Service will govern any disputes arising before the effective date of the Updated Terms.</p>
<p>We reserve the right to force forfeiture of any username for any reason.</p>
<p>We may, but have no obligation to, remove, edit, block, and/or monitor Content or accounts containing Content that we determine in our sole discretion violates these Terms of Service.</p>
<p>You are solely responsible for your interaction with other users of the Service, whether online or offline. You agree that Starsona is not responsible or liable for the conduct of any user.</p>
<p>Starsona reserves the right, but has no obligation, to monitor or become involved in disputes between you and other users. Exercise common sense and your best judgment when interacting with others, including when you request, submit, or post Content or any personal or other information.</p>
<p>Except as otherwise permitted under this Agreement or with our express permission you may not copy, display, distribute, or otherwise use individual elements of videos, or edits of videos, or remove any watermarking or attributive text generated in connection with the videos.</p>
<p>There may be links from the Service, or from communications you receive from the Service, to third-party web sites or features. There may also be links to third-party web sites or features in images or comments within the Service. The Service also includes third-party content that we do not control, maintain or endorse. Functionality on the Service may also permit interactions between the Service and a third-party web site or feature, including applications that connect the Service or your profile on the Service with a third-party web site or feature. For example, the Service may include a feature that enables you to share Content from the Service or your Content with a third party, which may be publicly posted on that third party’s service or application. Using this functionality typically requires you to login to your account on the third-party service and you do so at your own risk. Starsona does not control any of these third-party web services or any of their content. You expressly acknowledge and agree that Starsona is in no way responsible or liable for any such third-party services or features. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH THIRD PARTIES FOUND THROUGH THE SERVICE ARE SOLELY BETWEEN YOU AND THE THIRD PARTY. You may choose, at your sole and absolute discretion and risk, to use applications that connect the Service or your profile on the Service with a third-party service (each, an “Application”) and such Application may interact with, connect to or gather and/or pull information from and to your Service profile. By using such Applications, you acknowledge and agree to the following: (i) if you use an Application to share information, you are consenting to information about your profile on the Service being shared; (ii) your use of an Application may cause personally identifying information to be publicly disclosed and/or associated with you, even if Starsona has not itself provided such information; and (iii) your use of an Application is at your own option and risk, and you will hold Starsona harmless for activity related to the Application.</p>
<p>You agree that you are responsible for all data charges you incur through use of the Service.</p>
<p>We prohibit crawling, scraping, caching or otherwise accessing any content on the Service via automated means, including but not limited to, user profiles, photos, and videos (except as may be the result of standard search engine protocols or technologies used by a search engine with Starsona’s express consent).</p>
<p>&nbsp;</p>
<h4>Rights</h4>
<p>Starsona does not claim ownership of any Content that you post on or through the Service. Instead, you hereby grant to Starsona a perpetual, non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license to use the Content that you post on or through the Service, subject to the Service’s Privacy Policy, available <a href="http://starsona.com/privacy-policy/">http://starsona.com/privacy-policy/</a> .&nbsp; Any information you transmit to Starsona that is not payment or financial information, whether by direct entry, submission, electronic mail or otherwise, including data, questions, comments, or suggestions, will be treated as non-confidential and non-proprietary and will become the property of Starsona. Such information may be used for any purpose, including but not limited to reproduction, solicitations, disclosure, transmission, publication, broadcast, and posting. Starsona shall be free to use any ideas, concepts, know-how, or techniques contained in any communication you send to Starsona by any other means for any purpose whatsoever, including, but not limited to, developing and marketing products using such information.</p>
<p>When posting Content through the service to request a video from a Star,&nbsp;you hereby grant to the Star a perpetual, non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license to use the Content that you post on or through the Service, subject to the Service’s Privacy Policy, available <a href="http://starsona.com/privacy-policy/">http://starsona.com/privacy-policy/</a> .&nbsp;&nbsp;You grant the Star the right to use the names that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Starsona and the Star for all claims resulting from content you supply. Starsona has the right but not the obligation to monitor and edit or remove any activity or content. Starsona and the Star take no responsibility and assumes no liability for any content posted by you or any third party.</p>
<p>Some of the Service is supported by advertising revenue and may display advertisements and promotions, and you hereby agree that Starsona may place such advertising and promotions on the Service or on, about, or in conjunction with your Content. The manner, mode and extent of such advertising and promotions are subject to change without specific notice to you.You acknowledge that we may not always identify paid services, sponsored content, or commercial communications as such.</p>
<p>You represent and warrant that: (i) you own the Content posted by you on or through the Service or otherwise have the right to grant the rights and licenses set forth in these Terms of Service; (ii) the posting and use of your Content on or through the Service does not violate, misappropriate or infringe on the rights of any third party, including, without limitation, privacy rights, publicity rights, copyrights, trademark and/or other intellectual property rights; (iii) you agree to pay for all royalties, fees, and any other monies owed by reason of Content you post on or through the Service; and (iv) you have the legal right and capacity to enter into these Terms of Service in your jurisdiction.</p>
<p>The Service contains content owned or licensed by Starsona (“Starsona Content”). Starsona Content is protected by copyright, trademark, patent, trade secret and other laws, and, as between you and Starsona, Starsona owns and retains all rights in the Starsona Content and the Service. The compilation (meaning the collection, arrangement and assembly) of all Content and Materials (as later defined) is also the exclusive property of Starsona and is protected by United States and international copyright laws. You will not remove, alter or conceal any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Starsona Content and you will not reproduce, modify, adapt, prepare derivative works based on, perform, display, publish, distribute, transmit, broadcast, sell, license or otherwise exploit the Starsona Content or Materials. Any unauthorized use of text or images may violate United States and international copyright laws, trademark laws, the laws of privacy and publicity, and applicable regulations and statutes. Neither Starsona nor its affiliates warrant or represent that your use of Content, Services, or any other Materials will not infringe rights of third parties.</p>
<p>The Starsona name and logo are trademarks of Starsona, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Starsona, except in accordance with our brand guidelines, which you can request by emailing us at support@starsona.com. In addition, all page headers, custom graphics, button icons and scripts, product names, and the domain name for Starsona are service marks, trademarks and/or trade dress of Starsona, and may not be copied, imitated or used, in whole or in part, without prior written permission from Starsona.</p>
<p>Although it is Starsona’s intention for the Service to be available as much as possible, there will be occasions when the Service may be interrupted, including, without limitation, for scheduled maintenance or upgrades, for emergency repairs, or due to failure of telecommunications links and/or equipment.</p>
<p>Starsona reserves the right to remove any Content from the Service for any reason, without prior notice. Content removed from the Service may continue to be stored by Starsona, including, without limitation, in order to comply with certain legal obligations, but may not be retrievable without a valid court order. Consequently, Starsona encourages you to maintain your own backup of your Content. In other words, Starsona is not a backup service and you agree that you will not rely on the Service for the purposes of Content backup or storage. Starsona will not be liable to you for any modification, suspension, or discontinuation of the Services, or the loss of any Content. You also acknowledge that the Internet may be subject to breaches of security and that the submission of Content or other information may not be secure.</p>
<p>You agree that Starsona is not responsible for, and does not endorse, Content posted within the Service. Starsona does not have any obligation to prescreen, monitor, edit, or remove any Content. If your Content violates these Terms of Service, you may bear legal responsibility for that Content.</p>
<p>Except as otherwise described in the Service’s Privacy Policy, available at <a href="http://starsona.com/privacy-policy/">http://starsona.com/privacy-policy/</a> as between you and Starsona, any Content will be non-confidential and non-proprietary and we will not be liable for any use or disclosure of Content. You acknowledge and agree that your relationship with Starsona is not a confidential, fiduciary, or other type of special relationship, and that your decision to submit any Content does not place Starsona in a position that is any different from the position held by members of the general public, including with regard to your Content. None of your Content will be subject to any obligation of confidence on the part of Starsona, and Starsona will not be liable for any use or disclosure of any Content you provide.</p>
<p>It is Starsona’s policy not to accept or consider content, information, ideas, suggestions or other materials other than those we have specifically requested and to which certain specific terms, conditions and requirements may apply. This is to avoid any misunderstandings if your ideas are similar to those we have developed or are developing independently. Accordingly, Starsona does not accept unsolicited materials or ideas, and takes no responsibility for any materials or ideas so transmitted. If, despite our policy, you choose to send us content, information, ideas, suggestions, or other materials, you further agree that Starsona is free to use any such content, information, ideas, suggestions or other materials, for any purposes whatsoever, including, without limitation, developing and marketing products and services, without any liability or payment of any kind to you.</p>
<p>&nbsp;</p>
<h4>Social Distribution</h4>
<p>Starsona grants you the limited, revocable permission, subject to the restrictions in this Agreement, to engage in the following personal uses of video or online greetings&nbsp; developed by Starsona as part of Starsona’s services (“Materials”) that include the ability to share Materials with others (“Social Distribution”): (a) sending Materials to friends or acquaintances or posting and displaying a copy of Materials on a personal, non-commercial website, provided that you do not charge for access to the Materials or associate those Materials with advertising; or (b) posting and displaying a copy of the Materials on a third-party website that permits users to post content, so long as the posting is allowed pursuant to the third-party website’s terms and conditions and policies, and provided that the third-party website does not charge for access to those materials or associate those materials with products, services or advertising.&nbsp; If you breach any of the provisions of the Terms of Service, the permissions granted in these Terms of Service are terminated.</p>
<p>If you engage in Social Distribution, you agree that you will not post any performance claims about a Starsona product or service through your Social Distribution and that only Starsona may make claims, promises or statements on behalf of Starsona about its products and services. You also agree that you will not imply that you and Starsona or any Starsona brand are affiliated in any way or that Starsona approves of your Social Distribution. Except as otherwise permitted by this Agreement, you may not make any use of or license, distribute, reproduce, or otherwise exploit any part of the Materials. Starsona may, and reserves the right to, revoke Starsona’s permission for Social Distribution at any time and for any reason, and you agree to immediately cease Social Distribution upon notice of revocation and to comply with any terms we post in connection with the Social Distribution of Materials.</p>
<p>&nbsp;</p>
<h4>Mobile features</h4>
<p>The Starsona Platforms may offer features and services that are available to you via your mobile phone or other mobile device. These features and services may include, without limitation, the ability to upload user Content to the Starsona Platforms, view user content on the Starsona Platforms, receive messages (e.g., SMS and MMS messages, in-App messages, and on-device notifications) from the Starsona Platforms, download applications to your mobile phone or device, or access Starsona Platforms features (collectively, the “Mobile Features”). We may charge you for Mobile Features. Also, standard messaging, data and other fees may be charged by your carrier. Fees and charges will appear on your mobile bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your carrier or mobile device. Contact your carrier with questions regarding these issues. If you have registered for Mobile Features, you agree that we may send communications to your mobile device regarding Starsona, or other parties, and collect information related to your use of the Mobile Features. You agree to notify us of any changes to your mobile number and update your account(s) on the Starsona Platforms to reflect any such changes. If you receive SMS or MMS messages from Starsona or one of the Platforms, you may opt-out of such messages by texting “STOP” to the applicable short code for the mobile feature. You may also text “HELP” or contact us for support.</p>
<p>In addition to the other restrictions and limitations contained in this Agreement, Starsona is not responsible for failures in the performance of Mobile Features, including but not limited to, the delivery of electronic messages or videos via the Mobile Features as a result of any technical issues. For example, Starsona is not responsible if your electronic message or video is not delivered because:</p>
<ul>
<li>the recipient declines delivery;</li>
<li>the recipient uses an unsupported carrier;</li>
<li>the recipient’s mobile device or computer cannot display video messages;</li>
<li>the recipient’s plan does not provide for video messaging;</li>
<li>the recipient’s carrier is unable to deliver messages to the recipient;</li>
<li>the recipient’s network connection is interrupted during message delivery; or</li>
<li>either your or the recipient’s carrier does not support video messaging.</li>
</ul>
<p>There may be other reasons for a delivery failure as well. Starsona does not provide refunds for electronic messages or videos that are not delivered due to technical issues for which Starsona is not responsible.</p>
<p>If you sign up to receive promotional or marketing text messages (including SMS and MMS messages) from us, you acknowledge and agree that we may send such messages using an auto-dialer to the number you provide. You acknowledge and agree that you are not required to receive our text messages, and that you are not required to agree to receive text messages as a condition of purchasing any property, goods, or services.</p>
<p>If Starsona provides functionality for you to send a video or link to a video via text message (including through the use of SMS and MMS technologies) and you send such a text message, you represent and warrant that you have the consent of the recipient to send that text message. You further acknowledge and agree that, as between you and Starsona, you are the sender of such a video or link to a video and Starsona acts merely as a delivery agent.</p>
<p>&nbsp;</p>
<h4>Social Features</h4>
<p>You may choose, at your sole and absolute discretion and risk, to use applications or other functionality that enable interactions between the Starsona Platforms and a third-party website or online service (each, an “Application”), such as linking your profile on any of the Starsona Platforms with a third-party website or enabling you to “like” a product or “share” content on other websites. Such Applications may interact with, connect to or gather and/or pull information from and to your profile on the Starsona Platforms. By using such Applications, you acknowledge and agree to the following: (i) if you use an Application to share information relating to your Starsona Platform accounts, you are consenting to the information about your account being shared; (ii) your use of an Application may cause personally identifying information to be publicly disclosed and/or associated with you, even if Starsona has not provided such information; and (iii) your use of an Application is at your own option and risk, and you will hold Starsona harmless for the sharing of information relating to your Starsona Platform accounts that results from your use of an Application. You must read all log-in boxes and other pop-up boxes closely for notices about sharing your account information with, through or by any other means identified on an Application.</p>
<p>&nbsp;</p>
<h4>Reviews, Comments, Communications, and Other Content</h4>
<p>You may post reviews, comments, photos, videos, and other content; send videos and other communications; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights (including publicity rights), or otherwise injurious to third parties or objectionable, and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of “spam” or unsolicited commercial electronic messages. You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a video or other content. Starsona reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.</p>
<p>If you do post content or submit material, and unless we indicate otherwise, you grant Starsona a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, perform, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Starsona and sub-licensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Starsona for all claims resulting from content you supply. Starsona has the right but not the obligation to monitor and edit or remove any activity or content. Starsona takes no responsibility and assumes no liability for any content posted by you or any third party.</p>
<p>&nbsp;</p>
<h4>Third-party links, Advertisements and Products</h4>
<p>Starsona may feature on the Starsona Platforms, in its newsletters, or in other communications to you, links to third-party websites, social media platforms, or other services. These may appear in the form of text links, advertisements, banners, buttons, integrated gift services, digital cash, digital gift certificates, or otherwise. Accordingly, you expressly acknowledge and agree that we are in no way affiliated with such third-party sites or otherwise responsible or liable for your use of any such third-party sites or online features. Your use of such services is subject to the terms and conditions established by such third-parties. THE INFORMATION, CONTENT, AND PRODUCTS (INCLUDING GOODS AND SERVICES) AVAILABLE THROUGH ANY THIRD-PARTY LINKS (COLLECTIVELY, “THIRD-PARTY PRODUCTS”) ARE OFFERED BY INDEPENDENT ENTITIES, WHICH ARE NOT AFFILIATED IN ANY WAY WITH STARSONA. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT STARSONA IS NOT RESPONSIBLE OR LIABLE TO YOU IN ANY WAY FOR YOUR USE OF THIRD PARTY SITES OR YOUR PURCHASE OF THIRD-PARTY PRODUCTS. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH THIRD-PARTIES FOUND THROUGH THE STARSONA PLATFORMS, INCLUDING, WITHOUT LIMITATION, THE PAYMENT AND DELIVERY OF PRODUCTS AND SERVICES, INCLUDING (IF APPLICABLE) IN-APP PURCHASES, GIFT CARDS AND ANY TERMS, CONDITIONS, WARRANTIES, AND REPRESENTATIONS ASSOCIATED WITH ANY SUCH DEALINGS, ARE SOLELY BETWEEN YOU AND THE THIRD-PARTY AND STARSONA IS NOT IN ANY WAY RESPONSIBLE FOR YOUR USE. STARSONA WILL NOT REIMBURSE OR INDEMNIFY YOU FOR ANY LOSSES YOU MAY INCUR AS A RESULT OF TRANSACTIONS WITH ANY THIRD-PARTY.</p>
<p>There may be circumstances where access to the Starsona Platforms is provided by a link located at another website. Neither Starsona nor its affiliates makes any representations or gives any warranties with respect to any information contained in or at these other sites and neither Starsona nor its affiliates shall be liable for any damages or injury arising from the content of these other sites. Neither Starsona nor its affiliates endorses the individuals, companies, or other similar entities, or any products, services or materials associated with such individuals, companies, or other similar entities, that provide a link to the Starsona Platforms.</p>
<p>&nbsp;</p>
<h4>Personal Account</h4>
<p>If you purchase any Products or Services on the Starsona Platform you will be required to register and set up a personal account (“Personal Account”). You are responsible for the accuracy of the information included in your Personal Account. Your Personal Account will be protected in accordance with our Privacy Policy. You are responsible for: (1) keeping your Personal Account up to date and updating information as necessary; and (2) maintaining the confidentiality of your Personal Account including all registration information and any passwords assigned to you. You agree to accept responsibility for all activity that occurs on your Personal Account. You may not: (1) use an account of another person with the intent to impersonate that person; or (2) use an account to which another person has rights without such person’s authorization. Failure to comply with the foregoing shall constitute a breach of this Agreement, which may result in immediate termination of your Personal Account.</p>
<p>You are responsible for all usage or activity on your Personal Account, including the use of the account by any third-party authorized by you to use your password. Any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your Personal Account in our sole discretion. Starsona reserves the right to disclose any personal information included in your Personal Account or related to your use of the Starsona Platforms, Products and Services (as hereinafter defined), to third-parties in the course of investigating abuse of our Products and Services and to forward such information to appropriate law enforcement agencies. You must notify Starsona of any known or suspected unauthorized use of your Personal Account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of your password or credit card information.</p>
<p>If you are under the age of 18, you may only purchase products or Services with the permission of a parent or guardian. Starsona reserves the right to refuse service, terminate accounts or cancel orders in its sole discretion. Starsona reserves the right to terminate your Personal Account for violation of any of these rules.</p>
<p>&nbsp;</p>
<p><strong>Data Protection</strong></p>
<p>Starsona processes user data in conjunction with the purpose of the service&nbsp; and in accordance with the terms of service. For the purpose of using the app or website, Starsona stores user data (for example, name, e-mail). This data shall only be used by Starsona to operate the service, shall be treated confidentially, and will not be forwarded to third parties that are not involved in the ordering or payment processes. The user has the right upon request to receive information regarding their personal data stored by us. In addition, the use has the right to correct inaccurate data, or request that this data be blocked or deleted insofar as no statutory obligation to retention applies.</p>
<p>&nbsp;</p>
<h4>Payment of Fees and Charges</h4>
<p>You agree that you will pay all fees and charges that may be accrued by or in connection with your Personal Account. Starsona reserves the right in its sole discretion to bill fees and charges to any of the payment methods you have included in your Personal Account. All information that you provide to us or our third party payment processor must be accurate, current and complete. YOU REPRESENT AND WARRANT THAT YOU HAVE THE LEGAL RIGHT TO USE ANY CREDIT CARD(S) OR OTHER PAYMENT MEANS USED TO INITIATE ANY TRANSACTION. Billing and payment occur at the time of purchase. Rates may change at any time. Verification of information applicable to a purchase may be required prior to our acceptance of any order. Starsona does not provide price protection or refunds if the price for particular products or Services previously purchased by you is lowered or is part of a promotional offer. All products or Services or promotional offerings are final and non-refundable.&nbsp; All purchases include applicable sales taxes in effect at the time of purchase and will be based on the bill-to address provided in the Personal Account. No customers are eligible for tax exemptions for purchases made on this site.</p>
<p>&nbsp;</p>
<h4>Methods of payment</h4>
<p>If you purchase Products and Services, you must provide a method of payment to Starsona, such as a credit card account number or a checking account number. Starsona will charge or debit the purchase price to your method of payment. Any service fee charges are non-refundable. In no event will Starsona be liable for any NSF or other bank fees resulting directly or indirectly from any debits to your checking account.</p>
<p>Certain Products and Services may be purchased through Premium SMS Billing. These charges are processed by your mobile phone carrier, and third-parties designated by your carrier. The charges will appear on your mobile phone bill during the next billing cycle after your purchase. Purchases made by Premium SMS are final and non-refundable, even in the event of technical incompatibility or non-functionality of the content. Questions or problems relating to Premium SMS Billing should be addressed to your mobile phone carrier.</p>
<p>If you purchase content through an App Platform, the App Platform will process your payment, subject to its own privacy policy and terms of use. For such purchases, we do not receive your credit or debit card data or other payment account details. We may share information with the app store about your purchase and download of the content for the purposes of confirming your purchase and successful download, resolving your questions or complaints, or authorizing a refund.</p>
<p>&nbsp;</p>
<h4>Photos, videos &amp; other media limitations</h4>
<p>The Starsona Platforms may not be used as a media storage service. We cannot guarantee the availability of media storage, or of the quality or resolution of any media saved on the Starsona Platforms. Additionally, we may reduce the size or resolution of any media you submit or receive on the Starsona Platforms in order to make them compatible with our systems and processes.</p>
<p>&nbsp;</p>
<h4>Widgets</h4>
<p>The Starsona Platforms may provide certain content that you may choose to include on your personal web page, blog, page on a social networking site, or similar page (“Personal Page”) by pasting into your Personal Page the HTML or other code provided by Starsona and labeled as embed code (or a similar identifying label) (“Widget”). Starsona grants you a limited, revocable license, subject to the restrictions in this Agreement, to include the Widget, as provided by Starsona (without editing) on your Personal Page only. You agree that you will not include or otherwise make available a Widget on a web page or website containing content that is distasteful, unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable (in Starsona’s sole opinion). As described in the “Disclaimer of Warranties” section of this Agreement, Starsona makes no specific warranties about Widgets. Starsona may discontinue providing the services necessary for the Widgets to operate at any time for any reason without any liability to you. In addition, Starsona may disable Widgets that you include on any Personal Page if you violate this Agreement (as determined by Starsona in its sole discretion) or for any or no reason, without any liability to you. You agree that Starsona’s license grant to you to use a Widget on your Personal Page does not provide you with any intellectual property rights, including copyrights, in the materials made available via any Widget. You agree to not sell, lease, hypothecate, transfer, license, distribute, reproduce, encumber or otherwise exploit the content made available in a Widget, in whole or in part, without the express written consent of Starsona. You agree to include, and not remove or alter, Starsona’s trademark, copyright or other proprietary rights notices, as provided by Starsona on the Widget. You also agree to not use (or attempt to use) the Widget to display content other than the content provided or intended by Starsona to be displayed via a particular Widget. Except as expressly stated otherwise, the Widget and any and all content provided through the Widget are subject to this Agreement in their entirety.</p>
<p>&nbsp;</p>
<h4>Purchase of Products and Services</h4>
<p>Some of the features of the Starsona Platforms, including the purchase of videos, other digital products, services, memberships and subscriptions (collectively, “Products and Services”), and the delivery thereof, will require you to pay a fee. You agree to pay those amounts shown to you during the checkout or similar process. The delivery of any Products and Services to you does not transfer any commercial or promotional rights in the Products and Services. You may not resell, rent, lease or provide the Products or Services to any person and you shall not modify, publish, participate in the transfer or sale of, reproduce, or create new works from, any of the Products or Services in whole or in part. You are specifically prohibited from using any of the Products or Services for commercial advertising or mass mailings of any kind. Starsona may also impose limits on certain features and services or restrict your access to parts or all of the Product and Services without notice or liability. Once you download a digital product from the Starsona Platform, it is your responsibility not to lose, destroy or damage it.</p>
<p>You understand that the Products and Services and content we provide on the Starsona Platforms is subject to change at any time, and that Products and Services and content may be added or removed at Starsona’s discretion. Such changes may include, among other things: the addition or removal of content, Products and Services, the requirement that you pay to have access to certain content, Products and Services and content, Products and Services that you have previously paid for being made available at no charge. We make reasonable efforts to accurately display the attributes of our products. The inclusion of any Products and Services on Starsona Platforms at a particular time does not imply or warrant that these Products and Services will be available at any time.</p>
<p>It is your responsibility to ascertain and obey all applicable local, state, federal and international laws (including minimum age requirements) in regard to the possession, use and sale of any item purchased through our site. By placing an order, you represent that the products ordered will be used only in a lawful manner. We reserve the right, with or without prior notice, to limit the available quantity of or discontinue any Product or Service; to honor, or impose conditions on the honoring of, any coupon, coupon code, promotional code or other similar promotions; to bar any user from making any or all purchase(s); and/or to refuse to provide any user with any Product or Service.</p>
<p>&nbsp;</p>
<h4>Additional terms of Sale</h4>
<p>If a request for content cannot be or has not been fulfilled within 7 days, Starsona will make a full refund for the amount charged to the requestor.</p>
<p>If a request for content is fulfilled by a content provider but Starsona is not successfully paid, or paid only in part, by the requestor due to refunds, charge-backs, disputes, fraud, discounts, promotions, or other events which caused Starsona to not retain payment (in whole or in part) for the transaction, Starsona will only pay the content provider based on the amount Starsona successfully collected.</p>
<p>In the event of payment disputes, Starsona reserves the final rights on decision making. We will make reasonable efforts to achieve customer satisfaction.</p>
<p>&nbsp;</p>
<h4>Digital Millennium Copyright Act</h4>
<p>If you are a copyright owner or an agent thereof and believe that any Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
<p>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
<p>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
<p>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</p>
<p>Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;</p>
<p>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
<p>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
<p>You may direct copyright infringement notifications to our DMCA Agent at 1049 El Monte Avenue, Suite 74C, Mountain View, CA, 94040. Email: DMCA@starsona.com. For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to Starsona customer service through support@starsona.com.</p>
<p>You acknowledge that if you fail to comply with all of the requirements of this Section, your DMCA notice may not be valid.</p>
<p>—</p>
<p>Counter-Notice. If you believe that your Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to post and use the material in your Content, you may send a counter-notice containing the following information to the Copyright Agent:</p>
<p>Your physical or electronic signature;</p>
<p>Identification of the Content that has been removed or to which access has been disabled and the location at which the Content appeared before it was removed or disabled;</p>
<p>A statement that you have a good faith belief that the Content was removed or disabled as a result of mistake or a misidentification of the Content; and</p>
<p>Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court in San Francisco, California, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</p>
<p>If a counter-notice is received by the Copyright Agent, Starsona may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed Content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the Content provider, member or user, the removed Content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at Starsona’s sole discretion.</p>
<p>&nbsp;</p>
<h4>Warranty Disclaimer</h4>
<p>YOU AGREE THAT YOUR USE OF THE SERVICES SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, STARSONA, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE PRODUCTS AND SERVICES AND YOUR USE THEREOF. STARSONA MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE’S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR PRODUCTS AND SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR PRODUCTS AND SERVICES BY ANY THIRD PARTY, AND/OR (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PRODUCTS AND SERVICES. STARSONA DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND STARSONA WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
<p>&nbsp;</p>
<h4>Limitation of Liability</h4>
<p>IN NO EVENT SHALL STARSONA, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR PRODUCTS AND SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR PRODUCTS AND SERVICES, (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR PRODUCTS AND SERVICES BY ANY THIRD PARTY, AND/OR (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
<p>YOU SPECIFICALLY ACKNOWLEDGE THAT STARSONA SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
<p>The Service is controlled and offered by Starsona from its facilities in the United States of America. Starsona makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>
<p>&nbsp;</p>
<h4>Indemnity</h4>
<p>To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless Starsona, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Products and Services; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that your Content caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the Products and Services.</p>
<p>&nbsp;</p>
<h4>Ability to Accept Terms of Service</h4>
<p>You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are over the age of 13, as the Service is not intended for children under 13.</p>
<p>&nbsp;</p>
<h4>Assignment</h4>
<p>These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Starsona without restriction.</p>
<p>&nbsp;</p>
<h4>General</h4>
<p>You agree that: (i) the Service shall be deemed solely based in California; and (ii) the Service shall be deemed a passive website that does not give rise to personal jurisdiction over Starsona, either specific or general, in jurisdictions other than California. These Terms of Service shall be governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles. Any claim or dispute between you and Starsona that arises in whole or in part from the Service shall be decided exclusively by a court of competent jurisdiction located in Santa Clara County, California.</p>
<p>These Terms of Service, together with the Privacy Notice at <a href="http://starsona.com/privacy-policy/">http://starsona.com/privacy-policy/</a> and any other legal notices published by Starsona on the Service, shall constitute the entire agreement between you and Starsona concerning the Service. If any provision of these Terms of Service is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and Starsona’s failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision. Starsona reserves the right to amend these Terms of Service at any time and without notice, and it is your responsibility to review these Terms of Service for any changes. Your use of the Service following any amendment of these Terms of Service will signify your assent to and acceptance of its revised terms. YOU AND Starsona AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
<p>&nbsp;</p>
<h4>Arbitration Terms and Conditions</h4>
<p>(1) Except as provided in these Terms of Service, Starsona and you agree to exclusively arbitrate all disputes and claims between us other than those based on any intellectual property right, title or interest whatsoever, including claims of infringement, directly or indirectly related to any and all Starsona’ products, components of, or materials in Starsona products and services. In all other respects, these terms pursuant to which you agree to arbitrate disputes are intended to be broadly interpreted. These terms include, but are not limited to:</p>
<ul>
<li>claims arising out of or relating to any aspect of the relationship between us, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory;</li>
<li>claims that arose before these terms or any prior agreement (including, but not limited to, claims relating to advertising);</li>
<li>claims that are currently the subject of purported class action litigation in which you are not a member of a certified class;</li>
<li>claims that may arise after termination of these Terms of Service;</li>
<li>claims challenging the validity of these Terms of Service including, without limitation, those based on unconscionability, duress and fraud.</li>
</ul>
<p>References to “Starsona,” “you,” and “us” include our respective subsidiaries, affiliates, agents, employees, predecessors-in-interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or devices under these Terms of Service or prior agreements between us. Notwithstanding the foregoing, either party may bring an individual action in small claims court. These terms do not preclude you from bringing issues to the attention of federal, state, or local agencies. Such agencies can, if the law allows, seek relief against us on your behalf. You agree that, by agreeing to these Terms of Service (or accepting these Terms of Service by your use of Starsona products or services), you and Starsona are each waiving the right to a trial by jury or to participate in a representative or class action in a court of law and any arbitration proceeding. These Terms of Service evidence a transaction in interstate commerce, and thus the Federal Arbitration Act governs the interpretation and enforcement of these Terms. These arbitration terms shall survive termination of these Terms.</p>
<p>(2) A party who intends to seek arbitration must first send to the other, by certified mail, nationally recognized overnight courier (such as Federal Express), or email (with delivery receipt requested), a written Notice of Dispute (“Notice”). The Notice to Starsona should be addressed to: (i) General Counsel, Starsona, 1049 El Monte Avenue, Suite 74C, Mountain View, CA, 94040 if by certified mail or overnight courier, or (ii) General Counsel at legal@Starsona.com if by email (“Notice Address”). [NOTE:&nbsp; If there is no General Counsel, include the appropriate officer and contact information.] The Notice must be submitted within one (1) year of the earlier of (i) the date the claim or dispute actually arose, or (ii) the date you knew, or reasonably should have known, of the basis, grounds, events or circumstances giving rise to the claim or dispute. If Starsona does not receive the Notice within the one (1) year period required, any right you have to arbitrate your claim or dispute will be null and void and any request to arbitrate or litigate shall be dismissed with prejudice by an arbitrator or court of competent jurisdiction. The Notice must (a) describe the nature and basis of the claim or dispute and the date on which it occurred or you became of aware of it; and (b) set forth the specific relief sought (“Demand”). Otherwise, if you timely submit a Notice but Starsona and you are unable to reach an agreement to resolve the claim within 30 days after the Notice is received, you or Starsona may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by Starsona or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or Starsona is entitled.</p>
<p>(3) If you choose to initiate arbitration, you are responsible for paying your portion of the filing fee which is currently $125 for claims under $10,000 but is subject to change by the arbitration provider. If you are financially unable to pay this fee, you may request Starsona pay the initial filing fee on your behalf by written request at the Notice Address. If you are determined to be the prevailing party in arbitration, the amount of the filing fee will be deducted by the arbitrator from any amounts awarded to you. If Starsona is determined to be the prevailing party, such amount will be due and payable to Starsona along with any other amounts awarded by the arbitrator. The arbitration will be governed by the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by these Terms, and will be administered by the AAA. The AAA Rules are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by writing to the Notice Address. The arbitrator is bound by these Terms. All issues are for the arbitrator to decide, except that issues relating to the scope and enforceability of these Terms and intellectual property matters as indicated above are for the court to decide. Unless Starsona and you agree otherwise, any arbitration hearings for claims of $10,000 or less, will be conducted solely on the basis of (i) documents submitted to the arbitrator, or (ii) through a telephonic hearing. If your claim exceeds $10,000, the right to an in-person hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based. Except as otherwise provided for herein, the parties will initially split the cost of all AAA filing, administration, and arbitrator fees for any arbitration initiated in accordance with the notice requirements above. If, however, the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all such fees will be governed by the AAA Rules. In such case, you agree to reimburse Starsona for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules.</p>
<p>(4) The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees and expenses, including reasonable attorneys’ fees and costs, at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits. If, after finding in your favor in any respect on the merits of your claim, the arbitrator issues an award to you, the arbitrator may include in the award reimbursement of all or a portion of those fees and expenses which you directly incurred in connection with the pursuit of your claim as the arbitrator deems appropriate, including reasonable attorneys’ fees and expenses, and Starsona shall pay such award, subject to any rights to appeal Starsona may pursue in accordance with applicable law or the AAA Rules. If, after finding in Starsona’s favor in any respect on the merits of your claim, the arbitrator issues an award to Starsona, the arbitrator may include in the award reimbursement of all or a portion of those fees and expenses which Starsona directly incurred in connection with your claim as the arbitrator deems appropriate, including reasonable attorneys’ fees and expenses, and you shall pay such award, subject to any rights to appeal you may pursue in accordance with applicable law or the AAA Rules.</p>
<p>(5) The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. YOU AND STARSONA AGREE THAT NEITHER PARTY WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER CUSTOMERS, OR ARBITRATE ANY CLAIM OR DISPUTE AS A REPRESENTATIVE OR CLASS ACTION OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. If this specific provision is found to be unenforceable, then the entirety of these terms shall be null and void.</p>
<p>(6) If Starsona makes any future change(s) to these Terms of Service (other than a change to the Notice Address) during any period of time in which you are entitled to receive or actually do receive services from Starsona or its partners, agents or representatives related in any way to the Starsona product(s) (or components or ancillary devices related thereto or services) including, without limitation, support or maintenance services, you may reject any such change by sending Starsona written notice within 30 days of the change to the Notice Address above. By rejecting any such change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of these Terms of Service. Otherwise, if you are or were not entitled to receive such services or did not actually received such services, we agree that the arbitration provisions in effect on the date of your acquisition of the Starsona product(s) and services will control all disputes and claims under these Terms of Service.</p>
<p>(7) NO CLASS ACTIONS. You may only resolve disputes with Starsona on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, consolidated or representative action. Class arbitrations, class actions, private attorney general actions, and consolidation with other arbitrations are not allowed.</p>
<p><strong>Last updated:&nbsp; January 7, 2019</strong></p>
    </TermsConditionsWrapper.Description>
      </Scrollbars>
      <TermsConditionsWrapper.ButtonWrapper className="align-center">
        <PrimaryButton onClick={props.agreeTermsConditions}>
          {TERMS.BUTTON_LABEL}
        </PrimaryButton>
      </TermsConditionsWrapper.ButtonWrapper>
    </TermsConditionsWrapper.ComponentWrapper>
  </TermsConditionsWrapper >
);

TermsAndConditions.propTypes = {
  agreeTermsConditions: PropTypes.func,
};
TermsAndConditions.defaultProps = {
  agreeTermsConditions: () => { },
};
